
services:
  frontend:
    image: terumoapp/terumo-web:RELEASE-v0.0.1
    ports:
      - "3000:80"
    depends_on:
      - service-search-monolith

  service-search-monolith:
    image: terumoapp/terumo-service-search-monolith:RELEASE-v0.0.1
    ports:
      - "5000:5000"
    environment:
      - API_BASEPATH=http://localhost:5000/image-service/glomerulos/
    volumes:
      - C:/Users/Maods/Documents/Development/Mestrado/terumo/apps/terumo-model-binary-glomerulus-hypercellularity/data/raw/:/src/db
    networks:
      - appnet

networks:
  appnet:
    driver: bridge